
name: 'Close Milestone'
description: 'Automatically closes milestones linked to pull requests upon closure'
inputs:
  secrets-token:
    description: 'The Secrets Github Token used for authenticating Github API calls.'
    required: true
runs:
  using: "composite"
  steps:
  - name: Run Close Milestone Script
    id: run-close-milestone-script
    run: ${{ github.action_path }}/close-milestone.sh
    shell: bash
    env:
      SECRETS_TOKEN: ${{ inputs.secrets-token }}
      REPOSITORY: ${{ github.repository }}
      PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      PULL_REQUEST_MILESTONE: ${{ toJSON(github.event.pull_request.milestone) }}
